package com.jfrogchina.guestbook.uitest;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AddNodeTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void addNode() {
        driver.get("http://39.107.229.178:2222/");
        driver.manage().window().setSize(new Dimension(1126, 618));
        driver.findElement(By.cssSelector(".fa-user-plus")).click();
        driver.findElement(By.id("name")).sendKeys("MikeSun");
        driver.findElement(By.id("email")).sendKeys("mengke@jfrogchina.com");
        driver.findElement(By.id("phoneNo")).sendKeys("13333333333");
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.findElement(By.cssSelector("td:nth-child(3)")).getText(), is("13333333333"));
        driver.close();
    }

    @Test
    public void upgradeNode() {
        driver.get("http://39.107.229.178:2222/");
        driver.manage().window().setSize(new Dimension(1126, 618));
        driver.findElement(By.cssSelector("td:nth-child(4) > .btn")).click();
        driver.findElement(By.id("phoneNo")).click();
        driver.findElement(By.id("phoneNo")).sendKeys("13333333332");
        driver.findElement(By.cssSelector(".btn")).click();
//        assertThat(driver.findElement(driver.findElement(By.cssSelector("td:nth-child(3)")).getText(),"13333333332"));
        driver.close();
    }
    @Test
    public void deleteNode() {
        driver.get("http://39.107.229.178:2222/");
        driver.manage().window().setSize(new Dimension(1126, 618));
        driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(5) > .btn")).click();
        driver.close();
    }
}
